#pragma once

#include <Arduino.h>
#include <stdint.h>
#include "app/spectrometer_types.h"

extern bool spectrometer_available;
extern SpectrometerModel spectrometer_model;

extern float par_coefficients[18]; // per-channel PAR conversion coefficients, indexed 0..channel_count-1

// ---------------------------------------------------------------------------
// Default AS7341 acquisition settings — must match initAS7341() in as7341_api.cpp
// ---------------------------------------------------------------------------
static constexpr uint8_t  kAs7341DefaultAtIME         = 100;
static constexpr uint16_t kAs7341DefaultAStep          = 999;
static constexpr float    kAs7341DefaultGainMultiplier  = 2.0f;   // AS7341_GAIN_2X = 2×
// One ASTEP tick is 2.78 µs. Expressed in **milliseconds**, because basic counts follow
// the ams AN000633 §2.1 convention (integration time in ms) — the same units every host
// script in this repo uses. Was 2.78e-6 (seconds) up to firmware 1.05, which made
// firmware basic counts 1000× the host ones; see CALIBRATION.md.
static constexpr float    kAs7341AStepTickMs           = 2.78e-3f;
static constexpr float    kAs7341DefaultIntTimeMs       =
    (kAs7341DefaultAtIME + 1.0f) * (kAs7341DefaultAStep + 1.0f) * kAs7341AStepTickMs;
// Scaling factor: old raw-based coeff × this = basic-count-based coeff at default settings
static constexpr float    kAs7341BasicCountScale        =
    kAs7341DefaultGainMultiplier * kAs7341DefaultIntTimeMs;

// A coefficient fitted against per-second basic counts × this = the per-ms equivalent.
// Used once, to migrate NVS-stored coefficients written by firmware ≤ 1.05.
static constexpr float    kBasicCountPerSecondToPerMs   = 1000.0f;
// Units convention of the coefficients in the "par_coeffs" NVS namespace.
// 0/absent = per-second (firmware ≤ 1.05), 1 = per-ms. loadpref() migrates on mismatch.
static constexpr uint32_t kParCoeffUnitsVersion         = 1;
static constexpr char     kParCoeffUnitsKey[]           = "units_ver";

// Default PAR coefficients for AS7341, pre-scaled for basic_count = raw / gain / int_time_ms.
// Original calibration values multiplied by kAs7341BasicCountScale so that at the default
// gain/integration settings the PAR result is identical to the original calibration.
// TODO(tier-2): replace the values below with the fleet `w`. The tier-2 cell of
// new_calibration_miniPAR/regression_PAR_miniPAR.ipynb prints a ready-to-paste
// kDefaultParCoefficients[18] (40.8063026f, 42.1780116f, ...); these are the legacy
// per-device fit instead, so a freshly flashed device reports PAR from coefficients
// nothing in this repo can reproduce - see CALIBRATION.md, "Current state and open
// items". When doing it: paste the printed array over this block, drop the
// `* kAs7341BasicCountScale` retrofit (the new values are already basic-count based),
// rebuild, and re-run the tier-3 sweep on anything that relied on the old defaults.
// Two things to know first. par_coeffs_fleet.json is still shrunk toward the
// PLACEHOLDER prior (prior_is_placeholder: true, lambda=0.03, LODO median 4.38%), so
// regenerate it with the CM-derived prior before this becomes the fleet default. And
// this array only reaches devices with an empty "par_coeffs" NVS namespace: anything
// already written via set_spec_coeff keeps its stored vector across a re-flash.
static constexpr float kDefaultParCoefficients[18] = {
     1.0947163691214081f  * kAs7341BasicCountScale,
     0.09447067722660155f * kAs7341BasicCountScale,
     0.19681138419847008f * kAs7341BasicCountScale,
     0.16474806285828358f * kAs7341BasicCountScale,
     0.1871980220095715f  * kAs7341BasicCountScale,
     0.12997367405923924f * kAs7341BasicCountScale,
     0.16852358846871307f * kAs7341BasicCountScale,
     0.06357869488305948f * kAs7341BasicCountScale,
    -0.10794982525254658f  * kAs7341BasicCountScale,
    -0.003041914118767322f * kAs7341BasicCountScale,
     0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f
};

// ---------------------------------------------------------------------------
// Spectral sensitivity correction — ams AN000633 §2.2 and §2.4
// ---------------------------------------------------------------------------
// Generated by new_calibration_miniPAR/spectralCalibration_miniPAR_LR1-B.ipynb. The
// provenance — dataset, 3 devices, per-device spread, CM source, LR1-B calibration file —
// is in new_calibration_miniPAR/spectral_coeffs_fleet.json.
//
//   §2.1  x_i = raw_i / (gain × t_int_ms)                        spectrometerGetBasicCountDivisor()
//   §2.2  s_i = max(x_i − kAs7341ChannelOffsetsBasic[i], 0)      ams default offsets
//   §2.4  E_i = kDefaultSpectralCoefficients[i] × s_i            irradiance-like per channel
//
// This is a DIFFERENT correction from kDefaultParCoefficients, fitted against a different
// reference: §2.4 against LR1-B irradiance through the published reconstruction matrix,
// the PAR weights against the Li-250A.
//
// Ten entries, not eighteen like kDefaultParCoefficients: these are the AS7341's ten
// reported channels, and padding with zeros would be a trap — a zero spectral coefficient
// multiplies a channel away, where a zero PAR weight merely ignores it. An AS7343 needs
// its own fit, so there is deliberately no default for it here.
//
// NOT APPLIED ANYWHERE IN THE FIRMWARE YET, deliberately: par_raw sums
// basic_count × par_coefficients[i] with no offset removal, and the fleet w in
// par_coeffs_fleet.json was fitted against exactly those uncorrected counts. Feeding
// par_raw the §2.4 values instead would invalidate every deployed w and its tier-3
// (a, b). Fold this in only together with a w refitted on corrected counts.
static constexpr float kAs7341ChannelOffsetsBasic[10] = {
    0.00196979f,             0.00724927f,            
    0.00319381f,             0.001314659f,           
    0.001468153f,            0.001858105f,           
    0.001762778f,            0.00521704f,            
    0.003f,                  0.001f,                 
};
static constexpr float kDefaultSpectralCoefficients[10] = {
    34.950663f,              65.2894836f,            
    72.6979968f,             63.2732637f,            
    56.7371096f,             52.9586602f,            
    48.7067812f,             42.6716697f,            
    31.5659855f,             5.78161791f,            
};

const char *spectrometerModelName(SpectrometerModel model);
bool initSpectrometer();
bool spectrometerPrepareLegacyCommand();
bool spectrometer_read();
bool spectrometer_read_raw();
bool spectrometer_set_led_current(uint16_t led_current_ma);
bool spectrometer_read_flash(uint16_t led_current_ma);

// Raw-helper accessors for non-JSON command output
bool spectrometerReadInto(SpectrometerResult *out);
uint16_t spectrometerSetLedCurrentSilent(uint16_t led_current_ma);
uint8_t spectrometerGetAtIME();
uint16_t spectrometerGetAStep();
uint8_t spectrometerGetGain();
// Returns gain × integration_time_ms for the current settings (divisor for basic counts)
float spectrometerGetBasicCountDivisor();

// ADC full scale for the current ATIME/ASTEP. Not a fixed 0xFFFF — see AN000633 p.7.
uint16_t spectrometerGetFullScale();

// Saturation reporting helpers. Kind is "none" | "analog" | "digital" | "both".
const char *spectrometerSaturationKind(const SpectrometerResult &result);
// Prints the per-channel digital mask as four hex digits, e.g. `0x003F`.
void spectrometerPrintSatMaskHex(const SpectrometerResult &result);
// Prints `0xMASK,<kind>` for raw (non-JSON) replies.
void spectrometerPrintSaturation(const SpectrometerResult &result);

bool spectrometerSetAtIMEValue(uint8_t atime_value);
bool spectrometerSetAStepValue(uint16_t astep_value);
bool spectrometerSetGainValue(int gain_value);

bool setCalibrationSlopeValue(float slope_value);
bool setCalibrationInterceptValue(float intercept_value);
float getCalibrationSlopeValue();
float getCalibrationInterceptValue();

void spectrometerPrintNotAvailableError();
void spectrometerPrintUnsupportedDeviceError();
void spectrometerPrintNotYetImplementedError();
void cmd_spectrometer_status();
void cmd_spectrometer_saturation();
void cmd_spectrometer_set_atime(int argc, const char *argv[]);
void cmd_spectrometer_set_astep(int argc, const char *argv[]);
void cmd_spectrometer_set_gain(int argc, const char *argv[]);
bool cmd_get_par_raw(float *out_par);
bool cmd_get_par(float *out_par);
bool set_calibration_slope(int argc, const char *argv[]);
bool set_calibration_intercept(int argc, const char *argv[]);
void cmd_get_calibration();
void cmd_set_dev_name(int ar, const char *argv[]);
char *cmd_get_dev_name();
bool cmd_set_spec_coeff(int argc, const char *argv[]);
bool cmd_get_spec_coeff(int argc, const char *argv[]);
void loadpref();




