; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
upload_speed = 115200
upload_flags = --no-stub
options =
  verbose=true

build_flags =
  -DDEBUG=0                    ; for debug prints, can be set to 0 to disable
  -DARDUINO_USB_MODE=1         ; use Hardware CDC (HWCDC) on GPIO18/19
  -DARDUINO_USB_CDC_ON_BOOT=1  ; remap Serial to USB CDC instead of UART0
  -DUSB_VID=0x16C0
  -DUSB_PID=0x0483
  '-DUSB_MANUFACTURER="Espressif"'
  '-DUSB_PRODUCT="USB Serial"'


lib_deps = 
  https://github.com/adafruit/Adafruit_AS7341.git
  https://github.com/bblanchon/ArduinoJson.git


